project:
  type: website
  output-dir: docs

metadata:
  site-url: "https://dkremmydas.github.io/mysite"

render:
  - "*.qmd"

resources:
  - "files/**"
  - "papers/**"
    
website:
  title: "Dimitrios Kremmydas"
  favicon: "/files/favicon-32x32.png"
  site-url: "https://dkremmydas.github.io/mysite"
  repo-url: "https://github.com/dkremmydas/kremmydas.github.io"
  
  navbar:
    pinned: true 
    
    left:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Conferences"
        href: conferences.qmd
      - text: "Projects"
        href: projects.qmd                
      - text: "Teaching"
        href: teaching.qmd
      #- text: "Blog"
      #  href: blog.qmd   
      - text: "CV"
        href: files/dkremmydas_cv.pdf
        target: _blank
   
    right: 
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: mailto:kremmydas@aua.gr
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-4444-1698
        target: _blank
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=HmB8YnQAAAAJ
        target: _blank
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/dkremmydas
        rel: me
        target: _blank
  
  page-footer:
    left: |
      <span>{{< fa brands orcid >}} <strong>ORCID</strong> <a href="https://orcid.org/0000-0002-4444-1698" target=_blank>0000-0002-4444-1698</a> </span>
    center: |
      <span>&copy; 2025 Dimitrios Kremmydas</span>
    right: |
      <span>Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
  
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
